name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main # Deploy on push to the main branch only

jobs:
  deploy:
    name: Deploy Flask App
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      SERVICE_NAME: "document-automation"
      REGION: "asia-southeast1"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Set Google Cloud Project
        run: gcloud config set project $PROJECT_ID

      - name: Configure Docker Authentication
        run: gcloud auth configure-docker gcr.io

      - name: Build and Push Docker Image
        run: |
          docker build -t gcr.io/$PROJECT_ID/$SERVICE_NAME .
          docker push gcr.io/$PROJECT_ID/$SERVICE_NAME

      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy $SERVICE_NAME \
            --image gcr.io/$PROJECT_ID/$SERVICE_NAME \
            --platform managed \
            --region $REGION \
            --allow-unauthenticated
